"""add ambulance dispatch fields

Revision ID: 1ae57cb116f7
Revises: 20cb63730b55
Create Date: 2026-04-13 16:14:05.441438

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1ae57cb116f7'
down_revision: Union[str, Sequence[str], None] = '20cb63730b55'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    incident_leg_enum = sa.Enum('DISPATCH_TO_SCENE', 'SCENE_TO_ETC', 'OFFLINE', name='incidentleg')
    incident_leg_enum.create(op.get_bind())
    
    op.add_column('dispatches', sa.Column('total_distance', sa.Float(), nullable=False, server_default=sa.text('0.0')))
    op.add_column('gps_history', sa.Column('incident_leg', sa.Enum('DISPATCH_TO_SCENE', 'SCENE_TO_ETC', 'OFFLINE', name='incidentleg'), nullable=True))
    op.add_column('gps_history', sa.Column('delta_distance', sa.Float(), nullable=False, server_default=sa.text('0.0')))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('gps_history', 'delta_distance')
    op.drop_column('gps_history', 'incident_leg')
    op.drop_column('dispatches', 'total_distance')
    # ### end Alembic commands ###
