"""Add missing columns to users table

Revision ID: 201257c7c789
Revises: 6ff702b09d19
Create Date: 2026-04-29 14:21:27.231297

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '201257c7c789'
down_revision: Union[str, Sequence[str], None] = '6ff702b09d19'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def table_exists(name):
    bind = op.get_bind()
    insp = sa.inspect(bind)
    return insp.has_table(name)

def column_exists(table, column):
    bind = op.get_bind()
    insp = sa.inspect(bind)
    if not insp.has_table(table):
        return False
    columns = insp.get_columns(table)
    return any(c['name'] == column for c in columns)

def upgrade() -> None:
    """Upgrade schema."""
    # Using non-native enums (VARCHAR + CHECK constraints) for maximum stability across environments.

    # ### commands auto generated by Alembic - please adjust! ###
    if not table_exists('accreditation_categories'):
        op.create_table('accreditation_categories',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(length=100), nullable=False),
        sa.Column('description', sa.String(length=255), nullable=True),
        sa.Column('is_active', sa.Boolean(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint('id')
        )
        op.create_index(op.f('ix_accreditation_categories_name'), 'accreditation_categories', ['name'], unique=True)
    
    if not table_exists('ambulance_types'):
        op.create_table('ambulance_types',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(length=100), nullable=False),
        sa.Column('description', sa.String(length=255), nullable=True),
        sa.Column('is_active', sa.Boolean(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint('id')
        )
        op.create_index(op.f('ix_ambulance_types_name'), 'ambulance_types', ['name'], unique=True)
    
    if not table_exists('system_audit_logs'):
        op.create_table('system_audit_logs',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('table_name', sa.String(length=50), nullable=False),
        sa.Column('record_id', sa.Integer(), nullable=False),
        sa.Column('action', sa.String(length=20), nullable=False),
        sa.Column('changes', sa.JSON(), nullable=True),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('timestamp', sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
        sa.PrimaryKeyConstraint('id')
        )
        op.create_index(op.f('ix_system_audit_logs_table_name'), 'system_audit_logs', ['table_name'], unique=False)
    
    if not table_exists('claim_audit_logs'):
        op.create_table('claim_audit_logs',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('claim_id', sa.Integer(), nullable=False),
        sa.Column('action', sa.Enum('APPROVE', 'REJECT', name='claimaction', native_enum=False), nullable=False),
        sa.Column('processed_by_id', sa.Integer(), nullable=False),
        sa.Column('rejection_reason', sa.String(length=255), nullable=True),
        sa.Column('timestamp', sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(['claim_id'], ['claims.id'], ),
        sa.ForeignKeyConstraint(['processed_by_id'], ['users.id'], ),
        sa.PrimaryKeyConstraint('id')
        )
    
    if not column_exists('ambulances', 'equipment'):
        op.add_column('ambulances', sa.Column('equipment', sa.String(length=500), nullable=True))
    if not column_exists('ambulances', 'roadworthiness_expiry'):
        op.add_column('ambulances', sa.Column('roadworthiness_expiry', sa.Date(), nullable=True))
    if not column_exists('ambulances', 'insurance_expiry'):
        op.add_column('ambulances', sa.Column('insurance_expiry', sa.Date(), nullable=True))
    if not column_exists('ambulances', 'facility_id'):
        op.add_column('ambulances', sa.Column('facility_id', sa.Integer(), nullable=True))
        op.create_foreign_key(None, 'ambulances', 'facilities', ['facility_id'], ['id'])
    
    if not column_exists('drugs', 'updated_at'):
        op.add_column('drugs', sa.Column('updated_at', sa.DateTime(), nullable=False, server_default=sa.text('now()')))
    
    if not column_exists('lgas', 'population'):
        op.add_column('lgas', sa.Column('population', sa.Integer(), nullable=False, server_default='0'))
    if not column_exists('lgas', 'updated_at'):
        op.add_column('lgas', sa.Column('updated_at', sa.DateTime(), nullable=False, server_default=sa.text('now()')))
    
    # QA Findings compliance_rating alter
    # We'll skip altering if it's already an enum or just wrap in try/except if needed, 
    # but since we use native_enum=False, it's safer.
    try:
        op.alter_column('qa_findings', 'compliance_rating',
                   existing_type=sa.VARCHAR(length=50),
                   type_=sa.Enum('COMPLIANT', 'PARTIALLY_COMPLIANT', 'NON_COMPLIANT', name='compliancerating', native_enum=False),
                   existing_nullable=False)
    except Exception:
        pass

    if not column_exists('states', 'population'):
        op.add_column('states', sa.Column('population', sa.Integer(), nullable=False, server_default='0'))
    if not column_exists('states', 'updated_at'):
        op.add_column('states', sa.Column('updated_at', sa.DateTime(), nullable=False, server_default=sa.text('now()')))
    
    # Manually add missing columns to users table
    if not column_exists('users', 'phone_number'):
        op.add_column('users', sa.Column('phone_number', sa.String(length=20), nullable=True))
        op.create_index(op.f('ix_users_phone_number'), 'users', ['phone_number'], unique=True)
    
    if not column_exists('users', 'created_at'):
        op.add_column('users', sa.Column('created_at', sa.DateTime(), nullable=False, server_default=sa.text('now()')))
    
    if not column_exists('users', 'updated_at'):
        op.add_column('users', sa.Column('updated_at', sa.DateTime(), nullable=False, server_default=sa.text('now()')))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('states', 'population')
    op.drop_column('states', 'updated_at')
    op.alter_column('qa_findings', 'compliance_rating',
               existing_type=sa.Enum('COMPLIANT', 'PARTIALLY_COMPLIANT', 'NON_COMPLIANT', name='compliancerating', native_enum=False),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.drop_column('lgas', 'updated_at')
    op.drop_column('lgas', 'population')
    op.drop_column('drugs', 'updated_at')
    op.drop_constraint(None, 'ambulances', type_='foreignkey')
    op.drop_column('ambulances', 'facility_id')
    op.drop_column('ambulances', 'insurance_expiry')
    op.drop_column('ambulances', 'roadworthiness_expiry')
    op.drop_column('ambulances', 'equipment')
    op.drop_table('claim_audit_logs')
    op.drop_index(op.f('ix_system_audit_logs_table_name'), table_name='system_audit_logs')
    op.drop_table('system_audit_logs')
    op.drop_index(op.f('ix_ambulance_types_name'), table_name='ambulance_types')
    op.drop_table('ambulance_types')
    op.drop_index(op.f('ix_accreditation_categories_name'), table_name='accreditation_categories')
    op.drop_table('accreditation_categories')
    
    # Manually remove missing columns from users table
    op.drop_index(op.f('ix_users_phone_number'), table_name='users')
    op.drop_column('users', 'updated_at')
    op.drop_column('users', 'created_at')
    op.drop_column('users', 'phone_number')
    
    # Enum types are non-native, so no manual type dropping needed.
    # ### end Alembic commands ###
