"""Make location fields nullable for USSD/SMS

Revision ID: 20cb63730b55
Revises: c911cedf074b
Create Date: 2026-04-13 14:04:49.448351

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '20cb63730b55'
down_revision: Union[str, Sequence[str], None] = 'c911cedf074b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('incidents', 'latitude',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('incidents', 'longitude',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('incidents', 'state_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('incidents', 'lga_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('incidents', 'lga_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('incidents', 'state_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('incidents', 'longitude',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('incidents', 'latitude',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    # ### end Alembic commands ###
