"""add_destination_facility_id_to_incident

Revision ID: 6ff702b09d19
Revises: f3dce6dc1c07
Create Date: 2026-04-13 17:12:48.518092

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6ff702b09d19'
down_revision: Union[str, Sequence[str], None] = 'f3dce6dc1c07'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('incidents', sa.Column('destination_facility_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_incidents_destination_facility_id'), 'incidents', ['destination_facility_id'], unique=False)
    op.create_foreign_key(None, 'incidents', 'users', ['destination_facility_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'incidents', type_='foreignkey')
    op.drop_index(op.f('ix_incidents_destination_facility_id'), table_name='incidents')
    op.drop_column('incidents', 'destination_facility_id')
    # ### end Alembic commands ###
