"""Add USSD/SMS support fields and CITIZEN role

Revision ID: c911cedf074b
Revises: 302d96555d23
Create Date: 2026-04-13 13:55:48.522877

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c911cedf074b'
down_revision: Union[str, Sequence[str], None] = '302d96555d23'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Create the Enum type manually for Postgres
    incident_channel = sa.Enum('APP', 'USSD', 'SMS', 'CALL', 'DISPATCHER', name='incidentchannel')
    incident_channel.create(op.get_bind())

    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('incidents', sa.Column('channel', sa.Enum('APP', 'USSD', 'SMS', 'CALL', 'DISPATCHER', name='incidentchannel'), nullable=False, server_default='APP'))
    op.add_column('incidents', sa.Column('location_confirmed', sa.Boolean(), nullable=False, server_default='true'))
    op.add_column('users', sa.Column('phone_number', sa.String(length=20), nullable=True))
    op.create_index(op.f('ix_users_phone_number'), 'users', ['phone_number'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_phone_number'), table_name='users')
    op.drop_column('users', 'phone_number')
    op.drop_column('incidents', 'location_confirmed')
    op.drop_column('incidents', 'channel')
    # ### end Alembic commands ###

    # Drop the Enum type
    incident_channel = sa.Enum('APP', 'USSD', 'SMS', 'CALL', 'DISPATCHER', name='incidentchannel')
    incident_channel.drop(op.get_bind())
