"""add_ambulance_run_sheet_system

Revision ID: f3dce6dc1c07
Revises: 1ae57cb116f7
Create Date: 2026-04-13 16:58:13.896442

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f3dce6dc1c07'
down_revision: Union[str, Sequence[str], None] = '1ae57cb116f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DELETE FROM run_sheets") # Clear old test data to allow NOT NULL constraint
    # Create the enum type manually since autogenerate missed it
    run_sheet_status = postgresql.ENUM('DRAFT', 'CREW_SIGNED', 'FULLY_SIGNED', name='runsheetstatus')
    run_sheet_status.create(op.get_bind())
    
    op.create_table('run_sheet_drug_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_sheet_id', sa.Integer(), nullable=False),
    sa.Column('drug_id', sa.Integer(), nullable=True),
    sa.Column('custom_drug_name', sa.String(length=255), nullable=True),
    sa.Column('dosage', sa.String(length=255), nullable=False),
    sa.Column('administered_at', sa.DateTime(), nullable=False),
    sa.Column('is_reimbursable', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['drug_id'], ['drugs.id'], ),
    sa.ForeignKeyConstraint(['run_sheet_id'], ['run_sheets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_run_sheet_drug_entries_run_sheet_id'), 'run_sheet_drug_entries', ['run_sheet_id'], unique=False)
    op.create_table('run_sheet_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_sheet_id', sa.Integer(), nullable=False),
    sa.Column('data_snapshot', sa.JSON(), nullable=False),
    sa.Column('saved_at', sa.DateTime(), nullable=False),
    sa.Column('saved_by_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['run_sheet_id'], ['run_sheets.id'], ),
    sa.ForeignKeyConstraint(['saved_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_run_sheet_history_run_sheet_id'), 'run_sheet_history', ['run_sheet_id'], unique=False)
    op.add_column('run_sheets', sa.Column('dispatch_id', sa.Integer(), nullable=False))
    op.add_column('run_sheets', sa.Column('patient_name', sa.String(length=255), nullable=True))
    op.add_column('run_sheets', sa.Column('age', sa.Integer(), nullable=True))
    op.add_column('run_sheets', sa.Column('gender', sa.String(length=20), nullable=True))
    op.add_column('run_sheets', sa.Column('chief_complaint', sa.String(length=1000), nullable=True))
    op.add_column('run_sheets', sa.Column('assessment', sa.String(length=2000), nullable=True))
    op.add_column('run_sheets', sa.Column('blood_pressure', sa.String(length=20), nullable=True))
    op.add_column('run_sheets', sa.Column('pulse_rate', sa.Integer(), nullable=True))
    op.add_column('run_sheets', sa.Column('respiratory_rate', sa.Integer(), nullable=True))
    op.add_column('run_sheets', sa.Column('oxygen_saturation', sa.Float(), nullable=True))
    op.add_column('run_sheets', sa.Column('temperature', sa.Float(), nullable=True))
    op.add_column('run_sheets', sa.Column('gcs', sa.Integer(), nullable=True))
    op.add_column('run_sheets', sa.Column('status', sa.Enum('DRAFT', 'CREW_SIGNED', 'FULLY_SIGNED', name='runsheetstatus'), nullable=False))
    op.add_column('run_sheets', sa.Column('crew_signature_id', sa.Integer(), nullable=True))
    op.add_column('run_sheets', sa.Column('etc_signature_id', sa.Integer(), nullable=True))
    op.drop_constraint(op.f('run_sheets_incident_id_key'), 'run_sheets', type_='unique')
    op.create_index(op.f('ix_run_sheets_dispatch_id'), 'run_sheets', ['dispatch_id'], unique=False)
    op.create_index(op.f('ix_run_sheets_incident_id'), 'run_sheets', ['incident_id'], unique=False)
    op.drop_constraint(op.f('run_sheets_etc_staff_id_fkey'), 'run_sheets', type_='foreignkey')
    op.drop_constraint(op.f('run_sheets_crew_id_fkey'), 'run_sheets', type_='foreignkey')
    op.create_foreign_key(None, 'run_sheets', 'users', ['crew_signature_id'], ['id'])
    op.create_foreign_key(None, 'run_sheets', 'users', ['etc_signature_id'], ['id'])
    op.create_foreign_key(None, 'run_sheets', 'dispatches', ['dispatch_id'], ['id'])
    op.drop_column('run_sheets', 'patient_data')
    op.drop_column('run_sheets', 'crew_id')
    op.drop_column('run_sheets', 'etc_signature')
    op.drop_column('run_sheets', 'drugs_administered')
    op.drop_column('run_sheets', 'is_locked')
    op.drop_column('run_sheets', 'crew_signature')
    op.drop_column('run_sheets', 'etc_staff_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('run_sheets', sa.Column('etc_staff_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('run_sheets', sa.Column('crew_signature', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('run_sheets', sa.Column('is_locked', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('run_sheets', sa.Column('drugs_administered', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('run_sheets', sa.Column('etc_signature', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('run_sheets', sa.Column('crew_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('run_sheets', sa.Column('patient_data', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'run_sheets', type_='foreignkey')
    op.drop_constraint(None, 'run_sheets', type_='foreignkey')
    op.drop_constraint(None, 'run_sheets', type_='foreignkey')
    op.create_foreign_key(op.f('run_sheets_crew_id_fkey'), 'run_sheets', 'users', ['crew_id'], ['id'])
    op.create_foreign_key(op.f('run_sheets_etc_staff_id_fkey'), 'run_sheets', 'users', ['etc_staff_id'], ['id'])
    op.drop_index(op.f('ix_run_sheets_incident_id'), table_name='run_sheets')
    op.drop_index(op.f('ix_run_sheets_dispatch_id'), table_name='run_sheets')
    op.create_unique_constraint(op.f('run_sheets_incident_id_key'), 'run_sheets', ['incident_id'], postgresql_nulls_not_distinct=False)
    op.drop_column('run_sheets', 'etc_signature_id')
    op.drop_column('run_sheets', 'crew_signature_id')
    op.drop_column('run_sheets', 'status')
    op.drop_column('run_sheets', 'gcs')
    op.drop_column('run_sheets', 'temperature')
    op.drop_column('run_sheets', 'oxygen_saturation')
    op.drop_column('run_sheets', 'respiratory_rate')
    op.drop_column('run_sheets', 'pulse_rate')
    op.drop_column('run_sheets', 'blood_pressure')
    op.drop_column('run_sheets', 'assessment')
    op.drop_column('run_sheets', 'chief_complaint')
    op.drop_column('run_sheets', 'gender')
    op.drop_column('run_sheets', 'age')
    op.drop_column('run_sheets', 'patient_name')
    op.drop_column('run_sheets', 'dispatch_id')
    op.drop_index(op.f('ix_run_sheet_history_run_sheet_id'), table_name='run_sheet_history')
    op.drop_table('run_sheet_history')
    op.drop_index(op.f('ix_run_sheet_drug_entries_run_sheet_id'), table_name='run_sheet_drug_entries')
    op.drop_table('run_sheet_drug_entries')
    # ### end Alembic commands ###
