"""add incident_drugs to medical_interventions

Revision ID: 0444d9620261
Revises: 695cee079547
Create Date: 2026-05-17 11:57:48.780607

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0444d9620261'
down_revision: Union[str, None] = '695cee079547'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('medical_interventions', sa.Column('incident_drugs', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('medical_interventions', 'incident_drugs')
    # ### end Alembic commands ###
