"""add_claims_runsheets_and_extensions

Revision ID: 0f390b88f871
Revises: 970b11a4e1be
Create Date: 2026-05-11 17:19:23.577619

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0f390b88f871'
down_revision: Union[str, None] = '970b11a4e1be'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('drugs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('dosage_form', sa.String(length=100), nullable=True),
    sa.Column('is_nhia_approved', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_drugs_id'), 'drugs', ['id'], unique=False)
    op.create_index(op.f('ix_drugs_name'), 'drugs', ['name'], unique=True)
    op.create_table('monitoring',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('no_of_transport', sa.Integer(), nullable=True),
    sa.Column('no_of_mamii_lgas', sa.Integer(), nullable=True),
    sa.Column('by_tricycle_ambulance', sa.Integer(), nullable=True),
    sa.Column('by_nurtw_driver', sa.Integer(), nullable=True),
    sa.Column('bls', sa.Integer(), nullable=True),
    sa.Column('labor_transportation', sa.Integer(), nullable=True),
    sa.Column('obstetric_transportation', sa.Integer(), nullable=True),
    sa.Column('neonatal_transportation', sa.Integer(), nullable=True),
    sa.Column('bemonc', sa.Integer(), nullable=True),
    sa.Column('cemonc', sa.Integer(), nullable=True),
    sa.Column('maternal_mortalities', sa.Integer(), nullable=True),
    sa.Column('neonatal_mortalities', sa.Integer(), nullable=True),
    sa.Column('remark', sa.Text(), nullable=True),
    sa.Column('state_id', sa.Integer(), nullable=True),
    sa.Column('date_added', sa.DateTime(timezone=True), nullable=True),
    sa.Column('added_by', sa.String(length=255), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_by', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['state_id'], ['states.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_monitoring_id'), 'monitoring', ['id'], unique=False)
    op.create_table('claim_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=255), nullable=False),
    sa.Column('value', sa.String(length=500), nullable=False),
    sa.Column('date_updated', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_by_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_claim_settings_id'), 'claim_settings', ['id'], unique=False)
    op.create_index(op.f('ix_claim_settings_key'), 'claim_settings', ['key'], unique=True)
    op.create_table('partners',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('organisation_name', sa.String(length=255), nullable=True),
    sa.Column('contact_person', sa.String(length=255), nullable=True),
    sa.Column('contact_phone', sa.String(length=20), nullable=True),
    sa.Column('address', sa.String(length=500), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_partners_id'), 'partners', ['id'], unique=False)
    op.create_table('system_audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('table_name', sa.String(length=50), nullable=True),
    sa.Column('record_id', sa.String(length=100), nullable=True),
    sa.Column('action', sa.String(length=20), nullable=True),
    sa.Column('changes', sa.JSON(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_system_audit_logs_id'), 'system_audit_logs', ['id'], unique=False)
    op.create_index(op.f('ix_system_audit_logs_table_name'), 'system_audit_logs', ['table_name'], unique=False)
    op.create_table('dispatches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('incident_id', sa.Integer(), nullable=True),
    sa.Column('ambulance_id', sa.Integer(), nullable=True),
    sa.Column('crew_id', sa.UUID(), nullable=True),
    sa.Column('dispatch_timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.Column('accepted_timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.Column('total_distance', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['ambulance_id'], ['ambulances.id'], ),
    sa.ForeignKeyConstraint(['crew_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dispatches_id'), 'dispatches', ['id'], unique=False)
    op.create_table('etc_intakes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('incident_id', sa.Integer(), nullable=True),
    sa.Column('hospital_id', sa.Integer(), nullable=True),
    sa.Column('arrival_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('initial_assessment', sa.String(length=1000), nullable=True),
    sa.Column('triage_category', sa.String(length=50), nullable=True),
    sa.Column('interventions', sa.String(length=1000), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospitals.id'], ),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('incident_id')
    )
    op.create_index(op.f('ix_etc_intakes_id'), 'etc_intakes', ['id'], unique=False)
    op.create_table('facility_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('partner_id', sa.Integer(), nullable=True),
    sa.Column('facility_name', sa.String(length=255), nullable=True),
    sa.Column('facility_type', sa.String(length=100), nullable=True),
    sa.Column('address', sa.String(length=500), nullable=True),
    sa.Column('state_id', sa.Integer(), nullable=True),
    sa.Column('lga_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', name='facilityrequeststatus', native_enum=False), nullable=True),
    sa.Column('rejection_reason', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['lga_id'], ['lgas.id'], ),
    sa.ForeignKeyConstraint(['partner_id'], ['partners.id'], ),
    sa.ForeignKeyConstraint(['state_id'], ['states.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('gps_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ambulance_id', sa.Integer(), nullable=True),
    sa.Column('incident_id', sa.Integer(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_paused', sa.Boolean(), nullable=True),
    sa.Column('incident_leg', sa.Enum('DISPATCH_TO_SCENE', 'SCENE_TO_ETC', 'OFFLINE', name='incidentleg'), nullable=True),
    sa.Column('delta_distance', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['ambulance_id'], ['ambulances.id'], ),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('incident_status_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('incident_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('CREATED', 'Reported', 'DISPATCHED', 'ACCEPTED', 'EN_ROUTE', 'AT_SCENE', 'PATIENT_LOADED', 'EN_ROUTE_TO_ETC', 'ARRIVED_AT_ETC', 'COMPLETED', 'CLOSED', name='incidentstatus', native_enum=False), nullable=True),
    sa.Column('changed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('changed_by_id', sa.UUID(), nullable=True),
    sa.Column('notes', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['changed_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('patients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=True),
    sa.Column('middle_name', sa.String(), nullable=True),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.Column('do_b', sa.Date(), nullable=True),
    sa.Column('sex', sa.String(length=20), nullable=True),
    sa.Column('phone_number', sa.String(length=20), nullable=True),
    sa.Column('nhia', sa.String(length=50), nullable=True),
    sa.Column('address', sa.String(length=500), nullable=True),
    sa.Column('incident_id', sa.Integer(), nullable=True),
    sa.Column('ambulance_id', sa.Integer(), nullable=True),
    sa.Column('etc_id', sa.Integer(), nullable=True),
    sa.Column('medical_interventions', sa.String(length=1000), nullable=True),
    sa.Column('notes', sa.String(length=1000), nullable=True),
    sa.Column('drugs', sa.String(length=500), nullable=True),
    sa.Column('runsheet', sa.String(length=255), nullable=True),
    sa.Column('extra_details', sa.String(length=1000), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_patients_id'), 'patients', ['id'], unique=False)
    op.create_table('pledges',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('partner_id', sa.Integer(), nullable=True),
    sa.Column('ambulance_count', sa.Integer(), nullable=True),
    sa.Column('target_state_id', sa.Integer(), nullable=True),
    sa.Column('target_lga_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'IN_PROGRESS', 'PARTIALLY_FULFILLED', 'FULFILLED', 'REJECTED', name='pledgestatus', native_enum=False), nullable=True),
    sa.Column('fulfilled_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['partner_id'], ['partners.id'], ),
    sa.ForeignKeyConstraint(['target_lga_id'], ['lgas.id'], ),
    sa.ForeignKeyConstraint(['target_state_id'], ['states.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('qa_findings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('incident_id', sa.Integer(), nullable=True),
    sa.Column('compliance_rating', sa.Enum('COMPLIANT', 'PARTIALLY_COMPLIANT', 'NON_COMPLIANT', name='compliancerating', native_enum=False), nullable=True),
    sa.Column('findings_text', sa.String(length=1000), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('qa_officer_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ),
    sa.ForeignKeyConstraint(['qa_officer_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('claims',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('incident_id', sa.Integer(), nullable=True),
    sa.Column('patient_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('claim_type', sa.Enum('AMBULANCE', 'ETC', name='claimtype', native_enum=False), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('patient_name', sa.String(length=255), nullable=True),
    sa.Column('ambulance_type', sa.String(length=50), nullable=True),
    sa.Column('incident_category', sa.String(length=100), nullable=True),
    sa.Column('nhia', sa.String(length=100), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('service_provider', sa.String(length=255), nullable=True),
    sa.Column('incident_date', sa.String(length=50), nullable=True),
    sa.Column('distance_covered', sa.Float(), nullable=True),
    sa.Column('distance_km', sa.Float(), nullable=True),
    sa.Column('total_price', sa.Float(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('review', sa.String(length=500), nullable=True),
    sa.Column('etc_review', sa.String(length=500), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('rejection_reason', sa.String(length=255), nullable=True),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('processed_by_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.ForeignKeyConstraint(['processed_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_claims_id'), 'claims', ['id'], unique=False)
    op.create_index(op.f('ix_claims_incident_id'), 'claims', ['incident_id'], unique=False)
    op.create_index(op.f('ix_claims_patient_id'), 'claims', ['patient_id'], unique=False)
    op.create_table('run_sheets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('incident_id', sa.Integer(), nullable=True),
    sa.Column('dispatch_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('patient_id', sa.Integer(), nullable=True),
    sa.Column('ambulance_id', sa.Integer(), nullable=True),
    sa.Column('route_from', sa.String(length=255), nullable=True),
    sa.Column('route_to', sa.String(length=255), nullable=True),
    sa.Column('take_off_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('arrival_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('total_minutes_to_hospital', sa.Float(), nullable=True),
    sa.Column('medic_user_id', sa.UUID(), nullable=True),
    sa.Column('hospice_user_id', sa.UUID(), nullable=True),
    sa.Column('patient_name', sa.String(length=255), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('gender', sa.String(length=20), nullable=True),
    sa.Column('chief_complaint', sa.String(length=1000), nullable=True),
    sa.Column('assessment', sa.String(length=2000), nullable=True),
    sa.Column('blood_pressure', sa.String(length=20), nullable=True),
    sa.Column('pulse_rate', sa.Integer(), nullable=True),
    sa.Column('respiratory_rate', sa.Integer(), nullable=True),
    sa.Column('oxygen_saturation', sa.Float(), nullable=True),
    sa.Column('temperature', sa.Float(), nullable=True),
    sa.Column('gcs', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'CREW_SIGNED', 'FULLY_SIGNED', name='runsheetstatus', native_enum=False), nullable=True),
    sa.Column('crew_signature_id', sa.UUID(), nullable=True),
    sa.Column('crew_signed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('etc_signature_id', sa.UUID(), nullable=True),
    sa.Column('etc_signed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('date_added', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['ambulance_id'], ['ambulances.id'], ),
    sa.ForeignKeyConstraint(['crew_signature_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['dispatch_id'], ['dispatches.id'], ),
    sa.ForeignKeyConstraint(['etc_signature_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['hospice_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ),
    sa.ForeignKeyConstraint(['medic_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_run_sheets_ambulance_id'), 'run_sheets', ['ambulance_id'], unique=False)
    op.create_index(op.f('ix_run_sheets_dispatch_id'), 'run_sheets', ['dispatch_id'], unique=False)
    op.create_index(op.f('ix_run_sheets_id'), 'run_sheets', ['id'], unique=False)
    op.create_index(op.f('ix_run_sheets_incident_id'), 'run_sheets', ['incident_id'], unique=False)
    op.create_index(op.f('ix_run_sheets_patient_id'), 'run_sheets', ['patient_id'], unique=False)
    op.create_table('claim_audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('claim_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.Enum('APPROVE', 'REJECT', name='claimaction', native_enum=False), nullable=True),
    sa.Column('processed_by_id', sa.UUID(), nullable=True),
    sa.Column('rejection_reason', sa.String(length=255), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['claim_id'], ['claims.id'], ),
    sa.ForeignKeyConstraint(['processed_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('run_sheet_drug_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_sheet_id', sa.Integer(), nullable=True),
    sa.Column('drug_id', sa.Integer(), nullable=True),
    sa.Column('custom_drug_name', sa.String(length=255), nullable=True),
    sa.Column('dosage', sa.String(length=255), nullable=True),
    sa.Column('administered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_reimbursable', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['drug_id'], ['drugs.id'], ),
    sa.ForeignKeyConstraint(['run_sheet_id'], ['run_sheets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_run_sheet_drug_entries_run_sheet_id'), 'run_sheet_drug_entries', ['run_sheet_id'], unique=False)
    op.create_table('run_sheet_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_sheet_id', sa.Integer(), nullable=True),
    sa.Column('data_snapshot', sa.JSON(), nullable=True),
    sa.Column('saved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('saved_by_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['run_sheet_id'], ['run_sheets.id'], ),
    sa.ForeignKeyConstraint(['saved_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_run_sheet_history_run_sheet_id'), 'run_sheet_history', ['run_sheet_id'], unique=False)
    op.create_foreign_key(None, 'ambulances', 'wards', ['ward_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'ambulances', type_='foreignkey')
    op.drop_index(op.f('ix_run_sheet_history_run_sheet_id'), table_name='run_sheet_history')
    op.drop_table('run_sheet_history')
    op.drop_index(op.f('ix_run_sheet_drug_entries_run_sheet_id'), table_name='run_sheet_drug_entries')
    op.drop_table('run_sheet_drug_entries')
    op.drop_table('claim_audit_logs')
    op.drop_index(op.f('ix_run_sheets_patient_id'), table_name='run_sheets')
    op.drop_index(op.f('ix_run_sheets_incident_id'), table_name='run_sheets')
    op.drop_index(op.f('ix_run_sheets_id'), table_name='run_sheets')
    op.drop_index(op.f('ix_run_sheets_dispatch_id'), table_name='run_sheets')
    op.drop_index(op.f('ix_run_sheets_ambulance_id'), table_name='run_sheets')
    op.drop_table('run_sheets')
    op.drop_index(op.f('ix_claims_patient_id'), table_name='claims')
    op.drop_index(op.f('ix_claims_incident_id'), table_name='claims')
    op.drop_index(op.f('ix_claims_id'), table_name='claims')
    op.drop_table('claims')
    op.drop_table('qa_findings')
    op.drop_table('pledges')
    op.drop_index(op.f('ix_patients_id'), table_name='patients')
    op.drop_table('patients')
    op.drop_table('incident_status_history')
    op.drop_table('gps_history')
    op.drop_table('facility_requests')
    op.drop_index(op.f('ix_etc_intakes_id'), table_name='etc_intakes')
    op.drop_table('etc_intakes')
    op.drop_index(op.f('ix_dispatches_id'), table_name='dispatches')
    op.drop_table('dispatches')
    op.drop_index(op.f('ix_system_audit_logs_table_name'), table_name='system_audit_logs')
    op.drop_index(op.f('ix_system_audit_logs_id'), table_name='system_audit_logs')
    op.drop_table('system_audit_logs')
    op.drop_index(op.f('ix_partners_id'), table_name='partners')
    op.drop_table('partners')
    op.drop_index(op.f('ix_claim_settings_key'), table_name='claim_settings')
    op.drop_index(op.f('ix_claim_settings_id'), table_name='claim_settings')
    op.drop_table('claim_settings')
    op.drop_index(op.f('ix_monitoring_id'), table_name='monitoring')
    op.drop_table('monitoring')
    op.drop_index(op.f('ix_drugs_name'), table_name='drugs')
    op.drop_index(op.f('ix_drugs_id'), table_name='drugs')
    op.drop_table('drugs')
    # ### end Alembic commands ###
