"""update_partner_and_add_usertype_and_token

Revision ID: 1ce0e071d23b
Revises: 9d92f77bc8fe
Create Date: 2026-06-07 21:08:28.966502

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1ce0e071d23b'
down_revision: Union[str, None] = '9d92f77bc8fe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('partners', sa.Column('user_type', sa.String(length=50), nullable=True))
    op.add_column('partners', sa.Column('token', sa.String(length=500), nullable=True))
    op.create_unique_constraint(None, 'partners', ['token'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'partners', type_='unique')
    op.drop_column('partners', 'token')
    op.drop_column('partners', 'user_type')
    # ### end Alembic commands ###
