"""add_verification_and_reset_columns_to_partner_user

Revision ID: 2260212b8a0d
Revises: 6c3c1539fc31
Create Date: 2026-06-07 22:07:37.666596

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2260212b8a0d'
down_revision: Union[str, None] = '6c3c1539fc31'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('partner_users', sa.Column('is_verified', sa.Boolean(), nullable=False, server_default=sa.false()))
    op.add_column('partner_users', sa.Column('verification_code', sa.String(length=50), nullable=True))
    op.add_column('partner_users', sa.Column('verification_code_expires_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('partner_users', sa.Column('reset_password_code', sa.String(length=50), nullable=True))
    op.add_column('partner_users', sa.Column('reset_password_code_expires_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('partner_users', 'reset_password_code_expires_at')
    op.drop_column('partner_users', 'reset_password_code')
    op.drop_column('partner_users', 'verification_code_expires_at')
    op.drop_column('partner_users', 'verification_code')
    op.drop_column('partner_users', 'is_verified')
    # ### end Alembic commands ###
