"""Add hospital_types table

Revision ID: 27664b55a1b1
Revises: d6787b823f51
Create Date: 2026-05-07 16:02:18.423922

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '27664b55a1b1'
down_revision: Union[str, None] = 'd6787b823f51'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hospital_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('date_added', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hospital_types_id'), 'hospital_types', ['id'], unique=False)
    op.create_index(op.f('ix_hospital_types_name'), 'hospital_types', ['name'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_hospital_types_name'), table_name='hospital_types')
    op.drop_index(op.f('ix_hospital_types_id'), table_name='hospital_types')
    op.drop_table('hospital_types')
    # ### end Alembic commands ###
