"""add_etc_interventions_table

Revision ID: 37d9ceb940e0
Revises: 0444d9620261
Create Date: 2026-05-17 15:08:08.730240

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '37d9ceb940e0'
down_revision: Union[str, None] = '0444d9620261'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('etc_interventions',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('drug_id', sa.Integer(), nullable=True),
    sa.Column('medical_intervention', sa.String(), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('dose', sa.Float(), nullable=True),
    sa.Column('diagnosis', sa.String(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('ambulance_id', sa.Integer(), nullable=True),
    sa.Column('emergency_treatment_center_id', sa.Integer(), nullable=True),
    sa.Column('incident_id', sa.Integer(), nullable=True),
    sa.Column('date_added', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_etc_interventions_id'), 'etc_interventions', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_etc_interventions_id'), table_name='etc_interventions')
    op.drop_table('etc_interventions')
    # ### end Alembic commands ###
