"""add profile_picture and is_password_changed to users

Revision ID: 3d0c91a57fa6
Revises: 95944a67e763
Create Date: 2026-05-09 13:13:42.405109

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3d0c91a57fa6'
down_revision: Union[str, None] = '95944a67e763'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Add profile_picture as nullable (default null for all existing rows)
    op.add_column('users', sa.Column('profile_picture', sa.String(), nullable=True))

    # Add is_password_changed with a server_default so existing rows get FALSE
    # then drop the server default so the column remains app-controlled going forward
    op.add_column('users', sa.Column(
        'is_password_changed',
        sa.Boolean(),
        nullable=False,
        server_default=sa.false()
    ))
    op.alter_column('users', 'is_password_changed', server_default=None)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_password_changed')
    op.drop_column('users', 'profile_picture')
    # ### end Alembic commands ###
