"""Add active_status to ambulances

Revision ID: 42b43b516af1
Revises: 1f15d79f77cd
Create Date: 2026-06-22 14:01:16.007378

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '42b43b516af1'
down_revision: Union[str, None] = '1f15d79f77cd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ambulances', sa.Column('active_status', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ambulances', 'active_status')
    # ### end Alembic commands ###
