"""Update added_by FK to partner_users

Revision ID: 568106086e16
Revises: ce8b8e7c283f
Create Date: 2026-06-15 13:14:43.927842

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '568106086e16'
down_revision: Union[str, None] = 'ce8b8e7c283f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('ambulances_added_by_fkey', 'ambulances', type_='foreignkey')
    op.create_foreign_key(None, 'ambulances', 'partner_users', ['added_by'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'ambulances', type_='foreignkey')
    op.create_foreign_key('ambulances_added_by_fkey', 'ambulances', 'partners', ['added_by'], ['id'])
    # ### end Alembic commands ###
