"""add vehicle details to ambulances

Revision ID: 618e7420da5c
Revises: b1ba3dd5d291
Create Date: 2026-05-10 17:48:14.735204

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '618e7420da5c'
down_revision: Union[str, None] = 'b1ba3dd5d291'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ambulances', sa.Column('plate_number', sa.String(), nullable=True))
    op.add_column('ambulances', sa.Column('make', sa.String(), nullable=True))
    op.add_column('ambulances', sa.Column('year', sa.String(), nullable=True))
    op.add_column('ambulances', sa.Column('model', sa.String(), nullable=True))
    op.add_column('ambulances', sa.Column('accreditation_type', sa.String(), nullable=True))
    op.add_column('ambulances', sa.Column('vehicle_ownership_type', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ambulances', 'vehicle_ownership_type')
    op.drop_column('ambulances', 'accreditation_type')
    op.drop_column('ambulances', 'model')
    op.drop_column('ambulances', 'year')
    op.drop_column('ambulances', 'make')
    op.drop_column('ambulances', 'plate_number')
    # ### end Alembic commands ###
