"""Update claim schema with ambulance and etc statuses

Revision ID: 696397e20716
Revises: d295558cecf2
Create Date: 2026-05-29 10:24:33.857023

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '696397e20716'
down_revision: Union[str, None] = 'd295558cecf2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.create_table removed as it already exists
    op.add_column('claims', sa.Column('ambulance_claim_status', sa.String(length=50), nullable=True))
    op.add_column('claims', sa.Column('etc_claim_status', sa.String(length=50), nullable=True))
    op.drop_column('claims', 'status')
    # op.create_index(op.f('ix_run_sheets_emergency_treatment_center_id'), 'run_sheets', ['emergency_treatment_center_id'], unique=False) removed
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_index(op.f('ix_run_sheets_emergency_treatment_center_id'), table_name='run_sheets') removed
    # op.create_index(op.f('ix_run_sheets_etc_id'), 'run_sheets', ['emergency_treatment_center_id'], unique=False) removed
    op.add_column('claims', sa.Column('status', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.drop_column('claims', 'etc_claim_status')
    op.drop_column('claims', 'ambulance_claim_status')
    # op.drop_table removed as it was not created here
    # ### end Alembic commands ###
