"""Update claim schema with ambulance and etc statuses

Revision ID: 696397e20716
Revises: d295558cecf2
Create Date: 2026-05-29 10:24:33.857023

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '696397e20716'
down_revision: Union[str, None] = 'd295558cecf2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transfer_forms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('incident_id', sa.Integer(), nullable=False),
    sa.Column('medic_user_id', sa.UUID(), nullable=True),
    sa.Column('hospice_user_id', sa.UUID(), nullable=True),
    sa.Column('patient_id', sa.Integer(), nullable=True),
    sa.Column('patient_ids', sa.JSON(), nullable=True),
    sa.Column('etc_id', sa.Integer(), nullable=False),
    sa.Column('run_sheet_id', sa.Integer(), nullable=False),
    sa.Column('approve', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['etc_id'], ['hospitals.id'], ),
    sa.ForeignKeyConstraint(['hospice_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ),
    sa.ForeignKeyConstraint(['medic_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.ForeignKeyConstraint(['run_sheet_id'], ['run_sheets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transfer_forms_etc_id'), 'transfer_forms', ['etc_id'], unique=False)
    op.create_index(op.f('ix_transfer_forms_id'), 'transfer_forms', ['id'], unique=False)
    op.create_index(op.f('ix_transfer_forms_incident_id'), 'transfer_forms', ['incident_id'], unique=False)
    op.create_index(op.f('ix_transfer_forms_patient_id'), 'transfer_forms', ['patient_id'], unique=False)
    op.create_index(op.f('ix_transfer_forms_run_sheet_id'), 'transfer_forms', ['run_sheet_id'], unique=False)
    op.add_column('claims', sa.Column('ambulance_claim_status', sa.String(length=50), nullable=True))
    op.add_column('claims', sa.Column('etc_claim_status', sa.String(length=50), nullable=True))
    op.drop_column('claims', 'status')
    op.drop_index(op.f('ix_run_sheets_etc_id'), table_name='run_sheets')
    op.create_index(op.f('ix_run_sheets_emergency_treatment_center_id'), 'run_sheets', ['emergency_treatment_center_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_run_sheets_emergency_treatment_center_id'), table_name='run_sheets')
    op.create_index(op.f('ix_run_sheets_etc_id'), 'run_sheets', ['emergency_treatment_center_id'], unique=False)
    op.add_column('claims', sa.Column('status', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.drop_column('claims', 'etc_claim_status')
    op.drop_column('claims', 'ambulance_claim_status')
    op.drop_index(op.f('ix_transfer_forms_run_sheet_id'), table_name='transfer_forms')
    op.drop_index(op.f('ix_transfer_forms_patient_id'), table_name='transfer_forms')
    op.drop_index(op.f('ix_transfer_forms_incident_id'), table_name='transfer_forms')
    op.drop_index(op.f('ix_transfer_forms_id'), table_name='transfer_forms')
    op.drop_index(op.f('ix_transfer_forms_etc_id'), table_name='transfer_forms')
    op.drop_table('transfer_forms')
    # ### end Alembic commands ###
