"""add_usertype_to_partner_user

Revision ID: 6c3c1539fc31
Revises: 4844df17be49
Create Date: 2026-06-07 21:20:48.632920

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6c3c1539fc31'
down_revision: Union[str, None] = '4844df17be49'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('partner_users', sa.Column('user_type', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('partner_users', 'user_type')
    # ### end Alembic commands ###
