"""Add is_active to IncidentType

Revision ID: 6c7613a1b1a1
Revises: d9b4ba42d495
Create Date: 2026-07-05 18:19:19.043819

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6c7613a1b1a1'
down_revision: Union[str, None] = 'd9b4ba42d495'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('incident_types', sa.Column('is_active', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('incident_types', 'is_active')
    # ### end Alembic commands ###
