"""create etc_interventions with is_old

Revision ID: 7a2bc9333cfb
Revises: f2dc8acad4a9
Create Date: 2026-05-31 06:01:59.257933

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7a2bc9333cfb'
down_revision: Union[str, None] = 'f2dc8acad4a9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('etc_interventions',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('drug_id', sa.Integer(), nullable=True),
    sa.Column('medical_intervention', sa.String(), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('dose', sa.Float(), nullable=True),
    sa.Column('diagnosis', sa.String(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('ambulance_id', sa.Integer(), nullable=True),
    sa.Column('emergency_treatment_center_id', sa.Integer(), nullable=True),
    sa.Column('incident_id', sa.Integer(), nullable=True),
    sa.Column('patient_id', sa.Integer(), nullable=True),
    sa.Column('date_added', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_old', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_etc_interventions_id'), 'etc_interventions', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_etc_interventions_id'), table_name='etc_interventions')
    op.drop_table('etc_interventions')
    # ### end Alembic commands ###
