"""add_etc_rejection_reason_to_claims

Revision ID: 8292c1c790de
Revises: a482d0a13d66
Create Date: 2026-05-31 23:05:03.735132

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8292c1c790de'
down_revision: Union[str, None] = 'a482d0a13d66'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
