"""Added transfer forms and run sheets

Revision ID: 86e571dfc7dd
Revises: e3f0f30028ac
Create Date: 2026-05-19 01:04:52.702680

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '86e571dfc7dd'
down_revision: Union[str, None] = 'e3f0f30028ac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
