"""Add ambulance_types table

Revision ID: 8b35900e0fab
Revises: 27664b55a1b1
Create Date: 2026-05-07 16:12:00.184813

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8b35900e0fab'
down_revision: Union[str, None] = '27664b55a1b1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ambulance_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('date_added', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ambulance_types_id'), 'ambulance_types', ['id'], unique=False)
    op.create_index(op.f('ix_ambulance_types_name'), 'ambulance_types', ['name'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ambulance_types_name'), table_name='ambulance_types')
    op.drop_index(op.f('ix_ambulance_types_id'), table_name='ambulance_types')
    op.drop_table('ambulance_types')
    # ### end Alembic commands ###
