"""add_incident_types_table_and_update_incidents_fk

Revision ID: 970b11a4e1be
Revises: eae7e9921a0e
Create Date: 2026-05-11 15:20:25.002331

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '970b11a4e1be'
down_revision: Union[str, None] = 'eae7e9921a0e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('incident_types',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('date_added', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_incident_types_id'), 'incident_types', ['id'], unique=False)
    op.create_index(op.f('ix_incident_types_name'), 'incident_types', ['name'], unique=True)
    op.add_column('incidents', sa.Column('incident_category_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'incidents', 'incident_types', ['incident_category_id'], ['id'])
    op.drop_column('incidents', 'incident_category')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('incidents', sa.Column('incident_category', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'incidents', type_='foreignkey')
    op.drop_column('incidents', 'incident_category_id')
    op.drop_index(op.f('ix_incident_types_name'), table_name='incident_types')
    op.drop_index(op.f('ix_incident_types_id'), table_name='incident_types')
    op.drop_table('incident_types')
    # ### end Alembic commands ###
