"""create partner connect tables

Revision ID: 972a89ccdc8d
Revises: 9d92f77bc8fe
Create Date: 2026-06-05 16:44:11.017079

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '972a89ccdc8d'
down_revision: Union[str, None] = '9d92f77bc8fe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('partner_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('middle_name', sa.String(length=100), nullable=True),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=True),
    sa.Column('organisation_name', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_partner_users_email'), 'partner_users', ['email'], unique=True)
    op.create_index(op.f('ix_partner_users_id'), 'partner_users', ['id'], unique=False)
    op.create_table('partner_ambulances',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ambulance_id_str', sa.String(length=50), nullable=True),
    sa.Column('plate_number', sa.String(length=50), nullable=True),
    sa.Column('make', sa.String(length=100), nullable=True),
    sa.Column('model', sa.String(length=100), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('accreditation_type', sa.String(length=50), nullable=True),
    sa.Column('state_id', sa.Integer(), nullable=True),
    sa.Column('lga_id', sa.Integer(), nullable=True),
    sa.Column('ward_id', sa.Integer(), nullable=True),
    sa.Column('facility_id', sa.Integer(), nullable=True),
    sa.Column('vehicle_ownership_type', sa.String(length=50), nullable=True),
    sa.Column('driver_name', sa.String(length=255), nullable=True),
    sa.Column('contact_number', sa.String(length=50), nullable=True),
    sa.Column('fuel_type', sa.String(length=100), nullable=True),
    sa.Column('other_fuel_type_option', sa.String(length=100), nullable=True),
    sa.Column('fuel_capacity', sa.String(length=50), nullable=True),
    sa.Column('communication_devices', sa.String(length=255), nullable=True),
    sa.Column('other_communication_device_option', sa.String(length=100), nullable=True),
    sa.Column('latitude', sa.String(length=50), nullable=True),
    sa.Column('longitude', sa.String(length=50), nullable=True),
    sa.Column('equipments', sa.String(length=500), nullable=True),
    sa.Column('road_worthiness_assessment_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('road_worthiness_status', sa.String(length=50), nullable=True),
    sa.Column('last_inspection_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('next_scheduled_maintenance', sa.DateTime(timezone=True), nullable=True),
    sa.Column('inspection_notes', sa.String(length=500), nullable=True),
    sa.Column('insurance_provider', sa.String(length=255), nullable=True),
    sa.Column('insurance_expiration_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('is_out_for_maintenance', sa.Boolean(), nullable=True),
    sa.Column('is_out_of_service', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('added_by_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['added_by_id'], ['partner_users.id'], ),
    sa.ForeignKeyConstraint(['facility_id'], ['hospitals.id'], ),
    sa.ForeignKeyConstraint(['lga_id'], ['lgas.id'], ),
    sa.ForeignKeyConstraint(['state_id'], ['states.id'], ),
    sa.ForeignKeyConstraint(['ward_id'], ['wards.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_partner_ambulances_ambulance_id_str'), 'partner_ambulances', ['ambulance_id_str'], unique=True)
    op.create_table('partner_facilities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('facility_id_str', sa.String(length=50), nullable=True),
    sa.Column('facility_name', sa.String(length=255), nullable=True),
    sa.Column('facility_type', sa.String(length=100), nullable=True),
    sa.Column('facility_location', sa.String(length=100), nullable=True),
    sa.Column('ownership_type', sa.String(length=100), nullable=True),
    sa.Column('communication_devices', sa.String(length=255), nullable=True),
    sa.Column('number_of_ambulance', sa.Integer(), nullable=True),
    sa.Column('address', sa.String(length=500), nullable=True),
    sa.Column('contact_information', sa.String(length=255), nullable=True),
    sa.Column('state_id', sa.Integer(), nullable=True),
    sa.Column('lga_id', sa.Integer(), nullable=True),
    sa.Column('ward_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('date_added', sa.DateTime(timezone=True), nullable=True),
    sa.Column('added_by_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['added_by_id'], ['partner_users.id'], ),
    sa.ForeignKeyConstraint(['lga_id'], ['lgas.id'], ),
    sa.ForeignKeyConstraint(['state_id'], ['states.id'], ),
    sa.ForeignKeyConstraint(['ward_id'], ['wards.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_partner_facilities_facility_id_str'), 'partner_facilities', ['facility_id_str'], unique=True)
    op.create_table('partner_pledges',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pledge_id_str', sa.String(length=50), nullable=True),
    sa.Column('contact_details', sa.String(length=255), nullable=True),
    sa.Column('donor_name', sa.String(length=255), nullable=True),
    sa.Column('pledge_type', sa.String(length=100), nullable=True),
    sa.Column('number_of_ambulance', sa.Integer(), nullable=True),
    sa.Column('ambulance_type_id', sa.Integer(), nullable=True),
    sa.Column('state_id', sa.Integer(), nullable=True),
    sa.Column('lga_id', sa.Integer(), nullable=True),
    sa.Column('ward_id', sa.Integer(), nullable=True),
    sa.Column('facility_id', sa.Integer(), nullable=True),
    sa.Column('pledge_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('delivery_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('date_added', sa.DateTime(timezone=True), nullable=True),
    sa.Column('added_by_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['added_by_id'], ['partner_users.id'], ),
    sa.ForeignKeyConstraint(['ambulance_type_id'], ['ambulance_types.id'], ),
    sa.ForeignKeyConstraint(['facility_id'], ['hospitals.id'], ),
    sa.ForeignKeyConstraint(['lga_id'], ['lgas.id'], ),
    sa.ForeignKeyConstraint(['state_id'], ['states.id'], ),
    sa.ForeignKeyConstraint(['ward_id'], ['wards.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_partner_pledges_pledge_id_str'), 'partner_pledges', ['pledge_id_str'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_partner_pledges_pledge_id_str'), table_name='partner_pledges')
    op.drop_table('partner_pledges')
    op.drop_index(op.f('ix_partner_facilities_facility_id_str'), table_name='partner_facilities')
    op.drop_table('partner_facilities')
    op.drop_index(op.f('ix_partner_ambulances_ambulance_id_str'), table_name='partner_ambulances')
    op.drop_table('partner_ambulances')
    op.drop_index(op.f('ix_partner_users_id'), table_name='partner_users')
    op.drop_index(op.f('ix_partner_users_email'), table_name='partner_users')
    op.drop_table('partner_users')
    # ### end Alembic commands ###
