"""remove claim_type

Revision ID: 9d92f77bc8fe
Revises: 8292c1c790de
Create Date: 2026-05-31 23:31:14.481920

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9d92f77bc8fe'
down_revision: Union[str, None] = '8292c1c790de'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('claims', sa.Column('etc_rejection_reason', sa.String(length=255), nullable=True))
    op.drop_column('claims', 'claim_type')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('claims', sa.Column('claim_type', sa.VARCHAR(length=9), autoincrement=False, nullable=True))
    op.drop_column('claims', 'etc_rejection_reason')
    # ### end Alembic commands ###
