"""add real_user_type and etc_id to users

Revision ID: a0a78c834b9f
Revises: 3d0c91a57fa6
Create Date: 2026-05-10 16:21:29.085707

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a0a78c834b9f'
down_revision: Union[str, None] = '3d0c91a57fa6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('real_user_type', sa.String(), nullable=True))
    op.add_column('users', sa.Column('etc_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'etc_id')
    op.drop_column('users', 'real_user_type')
    # ### end Alembic commands ###
