"""Add distance_covered to run_sheets

Revision ID: a482d0a13d66
Revises: 7a2bc9333cfb
Create Date: 2026-05-31 21:55:40.752447

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a482d0a13d66'
down_revision: Union[str, None] = '7a2bc9333cfb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('run_sheets', sa.Column('distance_covered', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('run_sheets', 'distance_covered')
    # ### end Alembic commands ###
