"""update_patient_model_to_json_and_int

Revision ID: b03b9778b864
Revises: 0f390b88f871
Create Date: 2026-05-12 01:51:15.241405

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b03b9778b864'
down_revision: Union[str, None] = '0f390b88f871'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop existing string columns
    op.drop_column('patients', 'sex')
    op.drop_column('patients', 'medical_interventions')
    op.drop_column('patients', 'notes')
    op.drop_column('patients', 'drugs')
    
    # Add modified type columns
    op.add_column('patients', sa.Column('sex', sa.Integer(), nullable=True))
    op.add_column('patients', sa.Column('medical_interventions', sa.JSON(), nullable=True))
    op.add_column('patients', sa.Column('notes', sa.JSON(), nullable=True))
    op.add_column('patients', sa.Column('drugs', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('patients', 'drugs',
               existing_type=sa.JSON(),
               type_=sa.VARCHAR(length=500),
               existing_nullable=True)
    op.alter_column('patients', 'notes',
               existing_type=sa.JSON(),
               type_=sa.VARCHAR(length=1000),
               existing_nullable=True)
    op.alter_column('patients', 'medical_interventions',
               existing_type=sa.JSON(),
               type_=sa.VARCHAR(length=1000),
               existing_nullable=True)
    op.alter_column('patients', 'sex',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)
    # ### end Alembic commands ###
