"""add state_name and event_status_type to ambulances

Revision ID: b1ba3dd5d291
Revises: a0a78c834b9f
Create Date: 2026-05-10 17:23:32.731349

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b1ba3dd5d291'
down_revision: Union[str, None] = 'a0a78c834b9f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ambulances', sa.Column('state_name', sa.String(), nullable=True))
    op.add_column('ambulances', sa.Column('event_status_type', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ambulances', 'event_status_type')
    op.drop_column('ambulances', 'state_name')
    # ### end Alembic commands ###
