"""add nhia_or_shia to hospitals

Revision ID: b5bcf1ce69d8
Revises: 618e7420da5c
Create Date: 2026-05-10 19:43:26.704126

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b5bcf1ce69d8'
down_revision: Union[str, None] = '618e7420da5c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hospitals', sa.Column('nhia_or_shia', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('hospitals', 'nhia_or_shia')
    # ### end Alembic commands ###
