"""update_monitoring_fields

Revision ID: b6961ecdc16a
Revises: 6c7613a1b1a1
Create Date: 2026-07-05 20:22:36.317949

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b6961ecdc16a'
down_revision: Union[str, None] = '6c7613a1b1a1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('monitoring', sa.Column('als', sa.Integer(), nullable=True))
    op.add_column('monitoring', sa.Column('helicopters', sa.Integer(), nullable=True))
    op.add_column('monitoring', sa.Column('community_volunteers', sa.Integer(), nullable=True))
    op.drop_column('monitoring', 'by_nurtw_driver')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('monitoring', sa.Column('by_nurtw_driver', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('monitoring', 'community_volunteers')
    op.drop_column('monitoring', 'helicopters')
    op.drop_column('monitoring', 'als')
    # ### end Alembic commands ###
