"""add_rejection_reason_to_incidents

Revision ID: b80c19d3e1ec
Revises: 930c23e1f94b
Create Date: 2026-05-17 01:49:33.123984

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b80c19d3e1ec'
down_revision: Union[str, None] = '930c23e1f94b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('incidents', sa.Column('rejection_reason', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('incidents', 'rejection_reason')
    # ### end Alembic commands ###
