"""Add reset_password_code to User

Revision ID: c79d58bb2b79
Revises: b6961ecdc16a
Create Date: 2026-07-05 21:22:45.095694

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c79d58bb2b79'
down_revision: Union[str, None] = 'b6961ecdc16a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('reset_password_code', sa.String(length=50), nullable=True))
    op.add_column('users', sa.Column('reset_password_code_expires_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'reset_password_code_expires_at')
    op.drop_column('users', 'reset_password_code')
    # ### end Alembic commands ###
