"""add_claim_images_table

Revision ID: c8fa5297004b
Revises: 37d9ceb940e0
Create Date: 2026-05-17 15:17:10.451385

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c8fa5297004b'
down_revision: Union[str, None] = '37d9ceb940e0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('claim_images',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('claim_id', sa.Integer(), nullable=True),
    sa.Column('claim_title', sa.String(length=500), nullable=True),
    sa.Column('incident_id', sa.Integer(), nullable=True),
    sa.Column('image_url', sa.String(length=1000), nullable=True),
    sa.Column('is_etc', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['claim_id'], ['claims.id'], ),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_claim_images_claim_id'), 'claim_images', ['claim_id'], unique=False)
    op.create_index(op.f('ix_claim_images_id'), 'claim_images', ['id'], unique=False)
    op.create_index(op.f('ix_claim_images_incident_id'), 'claim_images', ['incident_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_claim_images_incident_id'), table_name='claim_images')
    op.drop_index(op.f('ix_claim_images_id'), table_name='claim_images')
    op.drop_index(op.f('ix_claim_images_claim_id'), table_name='claim_images')
    op.drop_table('claim_images')
    # ### end Alembic commands ###
