"""make transfer_form.run_sheet_id nullable

Revision ID: ce3c1d68a2bf
Revises: 42b43b516af1
Create Date: 2026-06-22 17:53:52.617823

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ce3c1d68a2bf'
down_revision: Union[str, None] = '42b43b516af1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('transfer_forms', 'run_sheet_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('transfer_forms', 'run_sheet_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
