"""Add status and added_by to ambulance

Revision ID: ce8b8e7c283f
Revises: 7b8210e3ca34
Create Date: 2026-06-15 11:37:24.649130

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ce8b8e7c283f'
down_revision: Union[str, None] = '7b8210e3ca34'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ambulances', sa.Column('status', sa.String(), nullable=True))
    op.add_column('ambulances', sa.Column('added_by', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'ambulances', 'partners', ['added_by'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'ambulances', type_='foreignkey')
    op.drop_column('ambulances', 'added_by')
    op.drop_column('ambulances', 'status')
    # ### end Alembic commands ###
