"""Add expanded operational data models and fields

Revision ID: d012b5fe66c9
Revises: 64d8285a3265
Create Date: 2026-05-11 15:34:12.623790

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd012b5fe66c9'
down_revision: Union[str, None] = '64d8285a3265'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('monitoring',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('no_of_transport', sa.Integer(), nullable=True),
    sa.Column('no_of_mamii_lgas', sa.Integer(), nullable=True),
    sa.Column('by_tricycle_ambulance', sa.Integer(), nullable=True),
    sa.Column('by_nurtw_driver', sa.Integer(), nullable=True),
    sa.Column('bls', sa.Integer(), nullable=True),
    sa.Column('labor_transportation', sa.Integer(), nullable=True),
    sa.Column('obstetric_transportation', sa.Integer(), nullable=True),
    sa.Column('neonatal_transportation', sa.Integer(), nullable=True),
    sa.Column('bemonc', sa.Integer(), nullable=True),
    sa.Column('cemonc', sa.Integer(), nullable=True),
    sa.Column('maternal_mortalities', sa.Integer(), nullable=True),
    sa.Column('neonatal_mortalities', sa.Integer(), nullable=True),
    sa.Column('remark', sa.Text(), nullable=True),
    sa.Column('state_id', sa.Integer(), nullable=True),
    sa.Column('date_added', sa.DateTime(timezone=True), nullable=True),
    sa.Column('added_by', sa.String(length=255), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_by', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['state_id'], ['states.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_monitoring_id'), 'monitoring', ['id'], unique=False)
    op.create_table('claim_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=255), nullable=False),
    sa.Column('value', sa.String(length=500), nullable=False),
    sa.Column('date_updated', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_by_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_claim_settings_id'), 'claim_settings', ['id'], unique=False)
    op.create_index(op.f('ix_claim_settings_key'), 'claim_settings', ['key'], unique=True)
    op.create_table('patients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=True),
    sa.Column('middle_name', sa.String(), nullable=True),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.Column('do_b', sa.Date(), nullable=True),
    sa.Column('sex', sa.String(length=20), nullable=True),
    sa.Column('phone_number', sa.String(length=20), nullable=True),
    sa.Column('nhia', sa.String(length=50), nullable=True),
    sa.Column('address', sa.String(length=500), nullable=True),
    sa.Column('incident_id', sa.Integer(), nullable=True),
    sa.Column('ambulance_id', sa.Integer(), nullable=True),
    sa.Column('etc_id', sa.Integer(), nullable=True),
    sa.Column('medical_interventions', sa.String(length=1000), nullable=True),
    sa.Column('notes', sa.String(length=1000), nullable=True),
    sa.Column('drugs', sa.String(length=500), nullable=True),
    sa.Column('runsheet', sa.String(length=255), nullable=True),
    sa.Column('extra_details', sa.String(length=1000), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_patients_id'), 'patients', ['id'], unique=False)
    op.add_column('claims', sa.Column('patient_id', sa.Integer(), nullable=True))
    op.add_column('claims', sa.Column('title', sa.String(length=255), nullable=True))
    op.add_column('claims', sa.Column('patient_name', sa.String(length=255), nullable=True))
    op.add_column('claims', sa.Column('ambulance_type', sa.String(length=50), nullable=True))
    op.add_column('claims', sa.Column('incident_category', sa.String(length=100), nullable=True))
    op.add_column('claims', sa.Column('nhia', sa.String(length=100), nullable=True))
    op.add_column('claims', sa.Column('location', sa.String(length=255), nullable=True))
    op.add_column('claims', sa.Column('service_provider', sa.String(length=255), nullable=True))
    op.add_column('claims', sa.Column('incident_date', sa.String(length=50), nullable=True))
    op.add_column('claims', sa.Column('distance_covered', sa.Float(), nullable=True))
    op.add_column('claims', sa.Column('total_price', sa.Float(), nullable=True))
    op.add_column('claims', sa.Column('review', sa.String(length=500), nullable=True))
    op.add_column('claims', sa.Column('etc_review', sa.String(length=500), nullable=True))
    op.alter_column('claims', 'status',
               existing_type=sa.VARCHAR(length=8),
               type_=sa.String(length=50),
               existing_nullable=True)
    op.create_index(op.f('ix_claims_patient_id'), 'claims', ['patient_id'], unique=False)
    op.create_foreign_key(None, 'claims', 'patients', ['patient_id'], ['id'])
    op.add_column('incidents', sa.Column('serial_no', sa.String(length=100), nullable=True))
    op.add_column('incidents', sa.Column('street', sa.String(length=255), nullable=True))
    op.add_column('incidents', sa.Column('district_ward', sa.String(length=255), nullable=True))
    op.add_column('incidents', sa.Column('area_council', sa.String(length=255), nullable=True))
    op.add_column('incidents', sa.Column('zip_code', sa.String(length=20), nullable=True))
    op.add_column('incidents', sa.Column('caller_is_patient', sa.String(length=10), nullable=True))
    op.add_column('incidents', sa.Column('incident_category', sa.String(length=100), nullable=True))
    op.add_column('incidents', sa.Column('triage_category', sa.String(length=50), nullable=True))
    op.add_column('incidents', sa.Column('description', sa.String(length=1000), nullable=True))
    op.add_column('incidents', sa.Column('recommendation', sa.String(length=1000), nullable=True))
    op.add_column('incidents', sa.Column('can_resolve_without_ambulance', sa.Boolean(), nullable=True))
    op.add_column('incidents', sa.Column('treatment_center', sa.String(length=255), nullable=True))
    op.add_column('incidents', sa.Column('referral_hospital_name', sa.String(length=255), nullable=True))
    op.add_column('incidents', sa.Column('hand_over_note', sa.String(length=1000), nullable=True))
    op.add_column('incidents', sa.Column('mass_casualty', sa.Boolean(), nullable=True))
    op.add_column('incidents', sa.Column('total_patients', sa.Integer(), nullable=True))
    op.add_column('incidents', sa.Column('incident_date', sa.String(length=50), nullable=True))
    op.add_column('incidents', sa.Column('incident_time', sa.String(length=50), nullable=True))
    op.add_column('incidents', sa.Column('dispatch_date', sa.String(length=50), nullable=True))
    op.add_column('incidents', sa.Column('ambulance_start', sa.DateTime(timezone=True), nullable=True))
    op.add_column('incidents', sa.Column('ambulance_stop', sa.DateTime(timezone=True), nullable=True))
    op.add_column('incidents', sa.Column('etc_start', sa.DateTime(timezone=True), nullable=True))
    op.add_column('incidents', sa.Column('etc_stop', sa.DateTime(timezone=True), nullable=True))
    op.add_column('incidents', sa.Column('treatment_stop', sa.DateTime(timezone=True), nullable=True))
    op.add_column('incidents', sa.Column('resolved', sa.Boolean(), nullable=True))
    op.add_column('incidents', sa.Column('time_resolved', sa.DateTime(timezone=True), nullable=True))
    op.add_column('incidents', sa.Column('dispatcher_id', sa.UUID(), nullable=True))
    op.add_column('incidents', sa.Column('dispatch_full_name', sa.String(length=255), nullable=True))
    op.add_column('incidents', sa.Column('date_added', sa.DateTime(timezone=True), nullable=True))
    op.add_column('incidents', sa.Column('added_by', sa.String(length=255), nullable=True))
    op.add_column('incidents', sa.Column('updated_by', sa.String(length=255), nullable=True))
    op.add_column('incidents', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.create_index(op.f('ix_incidents_serial_no'), 'incidents', ['serial_no'], unique=False)
    op.create_foreign_key(None, 'incidents', 'users', ['dispatcher_id'], ['id'])
    op.add_column('run_sheets', sa.Column('title', sa.String(length=255), nullable=True))
    op.add_column('run_sheets', sa.Column('patient_id', sa.Integer(), nullable=True))
    op.add_column('run_sheets', sa.Column('ambulance_id', sa.Integer(), nullable=True))
    op.add_column('run_sheets', sa.Column('route_from', sa.String(length=255), nullable=True))
    op.add_column('run_sheets', sa.Column('route_to', sa.String(length=255), nullable=True))
    op.add_column('run_sheets', sa.Column('take_off_time', sa.DateTime(timezone=True), nullable=True))
    op.add_column('run_sheets', sa.Column('arrival_time', sa.DateTime(timezone=True), nullable=True))
    op.add_column('run_sheets', sa.Column('total_minutes_to_hospital', sa.Float(), nullable=True))
    op.add_column('run_sheets', sa.Column('medic_user_id', sa.UUID(), nullable=True))
    op.add_column('run_sheets', sa.Column('hospice_user_id', sa.UUID(), nullable=True))
    op.add_column('run_sheets', sa.Column('date_added', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_run_sheets_ambulance_id'), 'run_sheets', ['ambulance_id'], unique=False)
    op.create_index(op.f('ix_run_sheets_patient_id'), 'run_sheets', ['patient_id'], unique=False)
    op.create_foreign_key(None, 'run_sheets', 'patients', ['patient_id'], ['id'])
    op.create_foreign_key(None, 'run_sheets', 'users', ['medic_user_id'], ['id'])
    op.create_foreign_key(None, 'run_sheets', 'users', ['hospice_user_id'], ['id'])
    op.create_foreign_key(None, 'run_sheets', 'ambulances', ['ambulance_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'run_sheets', type_='foreignkey')
    op.drop_constraint(None, 'run_sheets', type_='foreignkey')
    op.drop_constraint(None, 'run_sheets', type_='foreignkey')
    op.drop_constraint(None, 'run_sheets', type_='foreignkey')
    op.drop_index(op.f('ix_run_sheets_patient_id'), table_name='run_sheets')
    op.drop_index(op.f('ix_run_sheets_ambulance_id'), table_name='run_sheets')
    op.drop_column('run_sheets', 'date_added')
    op.drop_column('run_sheets', 'hospice_user_id')
    op.drop_column('run_sheets', 'medic_user_id')
    op.drop_column('run_sheets', 'total_minutes_to_hospital')
    op.drop_column('run_sheets', 'arrival_time')
    op.drop_column('run_sheets', 'take_off_time')
    op.drop_column('run_sheets', 'route_to')
    op.drop_column('run_sheets', 'route_from')
    op.drop_column('run_sheets', 'ambulance_id')
    op.drop_column('run_sheets', 'patient_id')
    op.drop_column('run_sheets', 'title')
    op.drop_constraint(None, 'incidents', type_='foreignkey')
    op.drop_index(op.f('ix_incidents_serial_no'), table_name='incidents')
    op.drop_column('incidents', 'is_active')
    op.drop_column('incidents', 'updated_by')
    op.drop_column('incidents', 'added_by')
    op.drop_column('incidents', 'date_added')
    op.drop_column('incidents', 'dispatch_full_name')
    op.drop_column('incidents', 'dispatcher_id')
    op.drop_column('incidents', 'time_resolved')
    op.drop_column('incidents', 'resolved')
    op.drop_column('incidents', 'treatment_stop')
    op.drop_column('incidents', 'etc_stop')
    op.drop_column('incidents', 'etc_start')
    op.drop_column('incidents', 'ambulance_stop')
    op.drop_column('incidents', 'ambulance_start')
    op.drop_column('incidents', 'dispatch_date')
    op.drop_column('incidents', 'incident_time')
    op.drop_column('incidents', 'incident_date')
    op.drop_column('incidents', 'total_patients')
    op.drop_column('incidents', 'mass_casualty')
    op.drop_column('incidents', 'hand_over_note')
    op.drop_column('incidents', 'referral_hospital_name')
    op.drop_column('incidents', 'treatment_center')
    op.drop_column('incidents', 'can_resolve_without_ambulance')
    op.drop_column('incidents', 'recommendation')
    op.drop_column('incidents', 'description')
    op.drop_column('incidents', 'triage_category')
    op.drop_column('incidents', 'incident_category')
    op.drop_column('incidents', 'caller_is_patient')
    op.drop_column('incidents', 'zip_code')
    op.drop_column('incidents', 'area_council')
    op.drop_column('incidents', 'district_ward')
    op.drop_column('incidents', 'street')
    op.drop_column('incidents', 'serial_no')
    op.drop_constraint(None, 'claims', type_='foreignkey')
    op.drop_index(op.f('ix_claims_patient_id'), table_name='claims')
    op.alter_column('claims', 'status',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=8),
               existing_nullable=True)
    op.drop_column('claims', 'etc_review')
    op.drop_column('claims', 'review')
    op.drop_column('claims', 'total_price')
    op.drop_column('claims', 'distance_covered')
    op.drop_column('claims', 'incident_date')
    op.drop_column('claims', 'service_provider')
    op.drop_column('claims', 'location')
    op.drop_column('claims', 'nhia')
    op.drop_column('claims', 'incident_category')
    op.drop_column('claims', 'ambulance_type')
    op.drop_column('claims', 'patient_name')
    op.drop_column('claims', 'title')
    op.drop_column('claims', 'patient_id')
    op.drop_index(op.f('ix_patients_id'), table_name='patients')
    op.drop_table('patients')
    op.drop_index(op.f('ix_claim_settings_key'), table_name='claim_settings')
    op.drop_index(op.f('ix_claim_settings_id'), table_name='claim_settings')
    op.drop_table('claim_settings')
    op.drop_index(op.f('ix_monitoring_id'), table_name='monitoring')
    op.drop_table('monitoring')
    # ### end Alembic commands ###
