"""add_patient_ids_to_transfer_forms

Revision ID: d295558cecf2
Revises: 5cff4af9c096
Create Date: 2026-05-28 17:00:47.312007

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd295558cecf2'
down_revision: Union[str, None] = '5cff4af9c096'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('run_sheets', sa.Column('emergency_treatment_center_id', sa.Integer(), nullable=True))
    op.add_column('run_sheets', sa.Column('price', sa.Float(), nullable=True))
    op.drop_index('ix_run_sheets_patient_id', table_name='run_sheets')
    op.drop_constraint('run_sheets_patient_id_fkey', 'run_sheets', type_='foreignkey')
    op.alter_column('run_sheets', 'patient_id',
               existing_type=sa.INTEGER(),
               type_=sa.JSON(),
               existing_nullable=True,
               postgresql_using='to_json(patient_id)')
    op.create_index(op.f('ix_run_sheets_emergency_treatment_center_id'), 'run_sheets', ['emergency_treatment_center_id'], unique=False)
    op.create_foreign_key(None, 'run_sheets', 'hospitals', ['emergency_treatment_center_id'], ['id'])
    op.add_column('transfer_forms', sa.Column('patient_ids', sa.JSON(), nullable=True))
    op.alter_column('transfer_forms', 'patient_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('transfer_forms', 'patient_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('transfer_forms', 'patient_ids')
    op.drop_constraint(None, 'run_sheets', type_='foreignkey')
    op.drop_index(op.f('ix_run_sheets_emergency_treatment_center_id'), table_name='run_sheets')
    op.alter_column('run_sheets', 'patient_id',
               existing_type=sa.JSON(),
               type_=sa.INTEGER(),
               existing_nullable=True,
               postgresql_using='NULL')
    op.create_index('ix_run_sheets_patient_id', 'run_sheets', ['patient_id'], unique=False)
    op.create_foreign_key('run_sheets_patient_id_fkey', 'run_sheets', 'patients', ['patient_id'], ['id'])
    op.drop_column('run_sheets', 'price')
    op.drop_column('run_sheets', 'emergency_treatment_center_id')
    # ### end Alembic commands ###
