"""Add status field to user

Revision ID: d9b4ba42d495
Revises: ce3c1d68a2bf
Create Date: 2026-06-25 10:20:27.046999

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd9b4ba42d495'
down_revision: Union[str, None] = 'ce3c1d68a2bf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('status', sa.Boolean(), nullable=True))
    op.execute('UPDATE users SET status = true WHERE status IS NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'status')
    # ### end Alembic commands ###
