"""Add status and added_by to hospital

Revision ID: e0c19bacdafb
Revises: 568106086e16
Create Date: 2026-06-16 13:53:57.185525

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e0c19bacdafb'
down_revision: Union[str, None] = '568106086e16'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hospitals', sa.Column('status', sa.String(), nullable=True))
    op.add_column('hospitals', sa.Column('added_by', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'hospitals', 'partner_users', ['added_by'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'hospitals', type_='foreignkey')
    op.drop_column('hospitals', 'added_by')
    op.drop_column('hospitals', 'status')
    # ### end Alembic commands ###
