"""create transfer forms table

Revision ID: e3f0f30028ac
Revises: 46b6f6fbd802
Create Date: 2026-05-18 23:24:33.740600

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e3f0f30028ac'
down_revision: Union[str, None] = '46b6f6fbd802'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transfer_forms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('incident_id', sa.Integer(), nullable=False),
    sa.Column('medic_user_id', sa.UUID(), nullable=True),
    sa.Column('hospice_user_id', sa.UUID(), nullable=True),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('etc_id', sa.Integer(), nullable=False),
    sa.Column('run_sheet_id', sa.Integer(), nullable=False),
    sa.Column('approve', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['etc_id'], ['hospitals.id'], ),
    sa.ForeignKeyConstraint(['hospice_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ),
    sa.ForeignKeyConstraint(['medic_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.ForeignKeyConstraint(['run_sheet_id'], ['run_sheets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transfer_forms_etc_id'), 'transfer_forms', ['etc_id'], unique=False)
    op.create_index(op.f('ix_transfer_forms_id'), 'transfer_forms', ['id'], unique=False)
    op.create_index(op.f('ix_transfer_forms_incident_id'), 'transfer_forms', ['incident_id'], unique=False)
    op.create_index(op.f('ix_transfer_forms_patient_id'), 'transfer_forms', ['patient_id'], unique=False)
    op.create_index(op.f('ix_transfer_forms_run_sheet_id'), 'transfer_forms', ['run_sheet_id'], unique=False)
    op.alter_column('gps_history', 'incident_leg',
               existing_type=postgresql.ENUM('DISPATCH_TO_SCENE', 'SCENE_TO_ETC', 'OFFLINE', name='incidentleg'),
               type_=sa.Enum('DISPATCH_TO_SCENE', 'SCENE_TO_ETC', 'OFFLINE', name='incidentleg', native_enum=False),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('gps_history', 'incident_leg',
               existing_type=sa.Enum('DISPATCH_TO_SCENE', 'SCENE_TO_ETC', 'OFFLINE', name='incidentleg', native_enum=False),
               type_=postgresql.ENUM('DISPATCH_TO_SCENE', 'SCENE_TO_ETC', 'OFFLINE', name='incidentleg'),
               existing_nullable=True)
    op.drop_index(op.f('ix_transfer_forms_run_sheet_id'), table_name='transfer_forms')
    op.drop_index(op.f('ix_transfer_forms_patient_id'), table_name='transfer_forms')
    op.drop_index(op.f('ix_transfer_forms_incident_id'), table_name='transfer_forms')
    op.drop_index(op.f('ix_transfer_forms_id'), table_name='transfer_forms')
    op.drop_index(op.f('ix_transfer_forms_etc_id'), table_name='transfer_forms')
    op.drop_table('transfer_forms')
    # ### end Alembic commands ###
