"""Add incidents table

Revision ID: eae7e9921a0e
Revises: b5bcf1ce69d8
Create Date: 2026-05-11 14:47:42.130318

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eae7e9921a0e'
down_revision: Union[str, None] = 'b5bcf1ce69d8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('incidents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('caller_name', sa.String(), nullable=True),
    sa.Column('caller_number', sa.String(), nullable=True),
    sa.Column('incident_date', sa.Date(), nullable=True),
    sa.Column('incident_time', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('recommendation', sa.Text(), nullable=True),
    sa.Column('triage_category', sa.String(), nullable=True),
    sa.Column('incident_location', sa.String(), nullable=True),
    sa.Column('district_ward', sa.String(), nullable=True),
    sa.Column('street', sa.String(), nullable=True),
    sa.Column('area_council', sa.String(), nullable=True),
    sa.Column('zip_code', sa.String(), nullable=True),
    sa.Column('incident_category', sa.String(), nullable=True),
    sa.Column('can_resolve_without_ambulance', sa.Boolean(), nullable=True),
    sa.Column('treatment_center', sa.String(), nullable=True),
    sa.Column('dispatch_full_name', sa.String(), nullable=True),
    sa.Column('dispatcher_id', sa.UUID(), nullable=True),
    sa.Column('dispatch_date', sa.Date(), nullable=True),
    sa.Column('supervisor_first_name', sa.String(), nullable=True),
    sa.Column('supervisor_middle_name', sa.String(), nullable=True),
    sa.Column('supervisor_last_name', sa.String(), nullable=True),
    sa.Column('supervisor_date', sa.Date(), nullable=True),
    sa.Column('serial_no', sa.String(), nullable=True),
    sa.Column('caller_is_patient', sa.String(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('mass_casualty', sa.Boolean(), nullable=True),
    sa.Column('total_patients', sa.Integer(), nullable=True),
    sa.Column('ambulance_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ambulance_stop', sa.DateTime(timezone=True), nullable=True),
    sa.Column('date_stop', sa.DateTime(timezone=True), nullable=True),
    sa.Column('incident_status_type', sa.String(), nullable=True),
    sa.Column('event_status_type', sa.String(), nullable=True),
    sa.Column('claims_approved', sa.String(), nullable=True),
    sa.Column('state_name', sa.String(), nullable=True),
    sa.Column('date_added', sa.DateTime(timezone=True), nullable=True),
    sa.Column('etc_id', sa.Integer(), nullable=True),
    sa.Column('ambulance_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['ambulance_id'], ['ambulances.id'], ),
    sa.ForeignKeyConstraint(['dispatcher_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['etc_id'], ['hospitals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_incidents_id'), 'incidents', ['id'], unique=False)
    op.create_index(op.f('ix_incidents_serial_no'), 'incidents', ['serial_no'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_incidents_serial_no'), table_name='incidents')
    op.drop_index(op.f('ix_incidents_id'), table_name='incidents')
    op.drop_table('incidents')
    # ### end Alembic commands ###
