"""Add incident types to monitoring

Revision ID: ef61c491c72e
Revises: c79d58bb2b79
Create Date: 2026-07-11 04:45:40.890342

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ef61c491c72e'
down_revision: Union[str, None] = 'c79d58bb2b79'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None
 

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('monitoring', sa.Column('paediatric_over_5', sa.Integer(), nullable=True))
    op.add_column('monitoring', sa.Column('drowning', sa.Integer(), nullable=True))
    op.add_column('monitoring', sa.Column('snake_bite', sa.Integer(), nullable=True))
    op.add_column('monitoring', sa.Column('other_weapons', sa.Integer(), nullable=True))
    op.add_column('monitoring', sa.Column('gunshot', sa.Integer(), nullable=True))
    op.add_column('monitoring', sa.Column('others', sa.Integer(), nullable=True))
    op.add_column('monitoring', sa.Column('paediatric_under_5', sa.Integer(), nullable=True))
    op.add_column('monitoring', sa.Column('neonatal_under_5', sa.Integer(), nullable=True))
    op.add_column('monitoring', sa.Column('obstetric_accident', sa.Integer(), nullable=True))
    op.add_column('monitoring', sa.Column('rta', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('monitoring', 'rta')
    op.drop_column('monitoring', 'obstetric_accident')
    op.drop_column('monitoring', 'neonatal_under_5')
    op.drop_column('monitoring', 'paediatric_under_5')
    op.drop_column('monitoring', 'others')
    op.drop_column('monitoring', 'gunshot')
    op.drop_column('monitoring', 'other_weapons')
    op.drop_column('monitoring', 'snake_bite')
    op.drop_column('monitoring', 'drowning')
    op.drop_column('monitoring', 'paediatric_over_5')
    # ### end Alembic commands ###
