"""add patient_id to etc_interventions

Revision ID: f2dc8acad4a9
Revises: 696397e20716
Create Date: 2026-05-30 07:34:46.281310

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f2dc8acad4a9'
down_revision: Union[str, None] = '696397e20716'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('etc_interventions', sa.Column('patient_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'etc_interventions', 'patients', ['patient_id'], ['id'])
    op.create_foreign_key(None, 'claim_audit_logs', 'claims', ['claim_id'], ['id'])
    op.create_foreign_key(None, 'claim_images', 'claims', ['claim_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'claim_images', type_='foreignkey')
    op.drop_constraint(None, 'claim_audit_logs', type_='foreignkey')
    op.drop_constraint(None, 'etc_interventions', type_='foreignkey')
    op.drop_column('etc_interventions', 'patient_id')
    # ### end Alembic commands ###
