from app.models.base import Base
from app.models.user import User
from app.models.state import State
from app.models.lga import LGA
from app.models.ward import Ward
from app.models.role import Role
from app.models.hospital_type import HospitalType
from app.models.ambulance_type import AmbulanceType
from app.models.hospital import Hospital
from app.models.ambulance import Ambulance
from app.models.incident_type import IncidentType
from app.models.incident import Incident
